### ISSUE TITLE
Friendly fire kinda is broken

### ISSUE THREAD

**Issue by Hyperexecube** [cortex-command-community/Cortex-Command-Community-Project-Data#133]
well it started when i loaded the game and i decided to use some addons and i off course picked friendly fire and when any unit shoots the bullet rips their hands of it makes the game unplayable with friendly fire

**Comment by garethyr** [comment]
I can't reproduce this. Did you perhaps have the fragile units script on at the same time? There was a bug in that that has since been fixed.
Also there's been a quiet preliminary bugfix version since pre4.0 that you can grab here, if you don't have it already: https://dl.orangedox.com/CCCP-Pre-Pre-Release-4.1.0
